name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair -v \
          -keystore netsom.jks \
          -storepass changeit \
          -keypass changeit \
          -alias netsom \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -dname "CN=Netsom, OU=Netsom, O=Netsom, L=Unknown, S=Unknown, C=US"

      - name: Convert keystore to base64
        run: base64 netsom.jks > key.txt

      - name: Show result
        run: cat key.txt
